name: Take Screenshot

on:
  push:
    branches: [main]

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.x'
        
    - name: Start Go application
      run: |
        go run ./cmd/web &
        
    - name: Take screenshot and upload as artifact
      run: node screenshot.js
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: screenshot.png
