name: Take Screenshot

on:
  push:
    branches: [screenshot]
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20.x'
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        
    - name: Start Go application
      run: |
        go run ./cmd/web

    - run: npm install puppeteer && npm install wait-on
        
    - name: Take screenshot
      run: node screenshot.js
      env:
        CHROME_BIN: chromium-browser
        DISPLAY: :99

    - name: Upload screenshot artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: screenshot.png
