name: Take Screenshot

on:
  push:
    branches: [screenshots]
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        
    - name: Start Go application
      run: |
        go build
        ./your-app-name &
        
    - name: Take screenshot
      run: node screenshot.js
      env:
        CHROME_BIN: chromium-browser
        DISPLAY: :99

    - name: Upload screenshot artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: screenshot.png
